server:
  port: 8085


eureka:
  client:
    security:
      basic:
        user: admin
        password: 123456
    service-url:
      defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@localhost:8761/eureka/

spring:
  application:
    name: provider